### ISSUE TITLE
Badge issue

### ISSUE THREAD

**Issue by aravind-j** [datacamp/r-package-parser#14]
Why is the badge of published package still showing as _not published_. 

https://www.rdocumentation.org/packages/germinationmetrics/versions/0.1.0

[![Rdoc](http://www.rdocumentation.org/badges/version/germinationmetrics)](http://www.rdocumentation.org/packages/germinationmetrics)

**Comment by aravind-j** [comment]
Migrated issue to [RDocumentation-app](https://github.com/datacamp/RDocumentation-app/issues/425)

**Comment by msberends** [comment]
See [#425](https://github.com/datacamp/RDocumentation-app/issues/425) and [#443](https://github.com/datacamp/RDocumentation-app/issues/443), bugs are still present and they are not responding. This problem is over a year old 😞
